server:
  port: ${PORT:8761}
  address: 0.0.0.0

spring:
  application:
    name: discovery-server

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

eureka:
  instance:
    hostname: ${EUREKA_HOST:${HOSTNAME:localhost}}
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0

logging:
  level:
    root: INFO
