server:
  port: 8090

spring:
  application:
    name: agent-crawler

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBITMQ_DEFAULT_USER}
    password: ${RABBITMQ_DEFAULT_PASS}
    template:
      mandatory: true

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      show-details: "when_authorized"


agent:
  nfj:
    start-url: "https://nofluffjobs.com/pl/it?device=mobile"
    initial-delay-ms: 60000
    interval-ms: 108000000

  solid:
    sitemap-url: "https://solid.jobs/sitemap.xml"
    initial-delay-ms: 60000
    interval-ms: 108000000

  theprotocol:
    sitemap-url: "https://static.theprotocol.it/sitemaps/CurrentOffers/SiteMapJobOffers1.xml"
    initial-delay-ms: 60000
    interval-ms: 108000000

  pracuj:
    initial-delay-ms: 60000
    interval-ms: 108000000

  playwright:
    headless: true

jobs:
  ingest:
    exchange: ingest.jobs
    routing:
      justjoinUrls: job-url.justjoin
      justjoinUrlsRetry: job-url.justjoin.retry
      justjoinUrlsDlq: job-url.justjoin.dlq
      nfjUrls: job-url.nfj
      nfjUrlsRetry: job-url.nfj.retry
      nfjUrlsDlq: job-url.nfj.dlq
      solidUrls: job-url.solid
      solidUrlsRetry: job-url.solid.retry
      solidUrlsDlq: job-url.solid.dlq
      theProtocolUrls: job-url.theprotocol
      theProtocolUrlsRetry: job-url.theprotocol.retry
      theProtocolUrlsDlq: job-url.theprotocol.dlq
      externalOffers: external-offer
    queue:
      justjoinUrls: ingest.jobs.url.justjoin
      justjoinUrlsRetry: ingest.jobs.url.justjoin.retry
      justjoinUrlsDlq: ingest.jobs.url.justjoin.dlq
      nfjUrls: ingest.jobs.url.nfj
      nfjUrlsRetry: ingest.jobs.url.nfj.retry
      nfjUrlsDlq: ingest.jobs.url.nfj.dlq
      solidUrls: ingest.jobs.url.solid
      solidUrlsRetry: ingest.jobs.url.solid.retry
      solidUrlsDlq: ingest.jobs.url.solid.dlq
      theProtocolUrls: ingest.jobs.url.theprotocol
      theProtocolUrlsRetry: ingest.jobs.url.theprotocol.retry
      theProtocolUrlsDlq: ingest.jobs.url.theprotocol.dlq
      externalOffers: ingest.jobs.external-offers

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 30
    leaseExpirationDurationInSeconds: 90

logging:
  level:
    root: INFO
    com.milosz.podsiadly: DEBUG
    org.springframework.amqp: INFO
